### PR TITLE
#65 - Ability To Renew Extend Link Expiration Dates

### LINKED ISSUE #65: Feature Request: Ability to renew/extend link expiration
When a link is generated with an expiration time, there is now way currently to extend that expiration. If a user is not able to get to the task you've given them in that certain time, it can be useful to just renew the link they already have instead of needing to generate a new one. It would be nice to have a tool or way to do this.

### PR DESCRIPTION
**Pull request by kodinkat**
fixes #65

### CODE REVIEW

**Comment by corsacca** [comment]
@kodinkat Can you give a summary here on what has been changed?

Should the Expires Column be blank?
image

**Comment by kodinkat** [comment]
>

**Comment by kodinkat** [comment]
> @kodinkat Can you give a summary here on what has been changed?
> 
> Should the Expires Column be blank? image

@corsacca 

- Both `View` & `Remove` functions have now been consolidated under options, along with new `Extend` feature.
- Extend feature now enables the extension of pre-existing links to a new expiry-date.
- Expires column should now be populated as soon as a new assigned user has been added - If users are pre-existing; with stale links; then I would expect to see column populated following a refresh.

Screenshot 2022-12-02 at 16 40 05

Screenshot 2022-12-02 at 16 41 17

**Comment by kodinkat** [comment]
Logic has now been updated to ensure, if available; a link's target expiry date to be shown within Expires Column.

**Comment by corsacca** [comment]
Thanks @kodinkat !

**Pull request merged**
