### PR TITLE
Add hook for updating table header

### PR DESCRIPTION
**Pull request by cairocoder01**
Adds a hook to be able to add extra content to the heading over the list of posts. My use case is adding a toggle to "Show All" and subsequently modify the query of which posts are returned from the `get_magic` API request.

This also updates the web components to the most recent version and gets them coming from NPM for easier updates in the future.

### CODE REVIEW

**Review by kodinkat — CHANGES_REQUESTED** [review]
Screenshot 2022-11-29 at 15 25 48

Blank rows detected - Could we have empty rows hidden if corresponding field is also hidden?

**Comment by cairocoder01** [comment]
Do you know which fields those are that are hidden? Just need to know how to reproduce that issue.

**Comment by cairocoder01** [comment]
@corsacca Are you able to test this and see if it works for you? @kodinkat and I haven't been able to track down the cause of his errors and want to eliminate the possibility that it is a one-off issue with his setup.

**Comment by cairocoder01** [comment]
Nevermind. Just found that it is a Safari issue with the web components themselves. I'm on it.

**Review by kodinkat — APPROVED** [review]

**Pull request merged**
