### PR TITLE
Post Connections template - beta

### PR DESCRIPTION
**Pull request by cairocoder01**
Adds a new Post Connections (beta) template for magic links which allows you to create a list of any post type related to any other post type (e.g. a contact's groups, a group's members, a contact's subassigned contacts)

This is marked as beta because there are more features to come like viewing and adding comments. I am submitting this now so that maybe it could be available for the upcoming virtual summit in a few weeks. 

Future features to be added:
- View/add comments
- Sort list
- Search/filter list

### CODE REVIEW

**Comment by corsacca** [comment]
Nice!
image

**Comment by corsacca** [comment]
@cairocoder01 
It took me a bit to understand how to set this type up.

I wonder if we can reverse the UI on this one so it lists the connection field on the selected post type's side.
image

Instead of thinking of the connected post type and which field the record appears in
"I want a list of the groups where my contact is in the members field"

We could directly say: this magic lists out the records in a field
"I want a list of the contact's groups"

**Comment by corsacca** [comment]
This is brilliant work by the way. I like the new UI too. Thank you!
I'm going to merge this in.

**Comment by cairocoder01** [comment]
@corsacca That makes sense about receiving the connection field. I think it even took me a bit to figure it out. I think what made me do this was something like subassigned where that field l connection is really only down on the child record. But I think there's still a hidden field on the parent that we can still use. I'll do that in an upcoming update.

**Pull request merged**
